yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'post'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_lists'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'

urlpatterns = [
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts'))
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField(
        verbose_name='Текст коментария',
    )
    created = models.DateTimeField(
        verbose_name='Дата',
        auto_now_add=True
    )

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower_client',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

    class Meta:
        ordering = ('author',)
        constraints = (models.UniqueConstraint(
            fields=['author', 'user'],
            name='unique_follow'),
        )

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].widget.attrs['placeholder'] = (
            'Напиши текст, пожалуйста'
        )
        self.fields['group'].empty_label = (
            'Выберите группу, если желаете 🙂'
        )

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': 'Введите текст',
            'group': 'Выберете группу'
        }
        help_texts = {
            'text': 'Попробуй ввести текст',
            'group': 'Выбор за тобой'
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Комментарий',
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render


from .forms import PostForm, CommentForm
from .models import Group, Post, User, Comment, Follow
from .utils import pagination


def index(request):
    posts = pagination(Post.objects.all(), request)
    return render(request, 'posts/index.html', posts)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    context = {
        'group': group
    }
    context.update(pagination(posts, request))
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user, author=author
    ).exists()
    context = {
        'author': author,
        'following': following
    }
    context.update(pagination(author.posts.all(), request))
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comments = Comment.objects.filter(post=post)
    form = CommentForm(request.POST or None)
    context = {
        'posts': post,
        'form': form,
        'comments': comments
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    is_edit = False
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=post.author)
    return render(request, 'posts/create_post.html', {
        'form': form, 'is_edit': is_edit
    }
    )


@login_required
def post_edit(request, post_id):
    is_edit = True
    user = request.user
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    context = {
        'post': post,
        'form': form,
        'is_edit': is_edit
    }
    if user != post.author:
        return redirect('post:post_detail', post.pk)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post.pk)
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    else:
        return render(request, 'posts/includes/comment.html', {'form': form})
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    following = Post.objects.filter(
        author__following__user=request.user)
    context = {}
    context.update(pagination(following, request))
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', author)


@login_required
def profile_unfollow(request, username):
    user = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=user).delete()
    return redirect('posts:profile', user)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}
  {% if is_edit %}
    Редактирование поста
  {% else %}
    Новая запись
  {% endif %}
{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        {% if is_edit %}
          Редактировать запись
        {% else %}
          Добавить запись
        {% endif %}
      </div>
      <div class="card-body">
        {% load user_filters %}
        {% if form.errors %}
          {% for field in form %}
            {% for error in field.errors %}
            <div class="alert alert-danger">
              {{ error|escape }}
            </div>
            {% endfor %}
          {% endfor %}
          {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
            {{ error|escape }}
          </div>
          {% endfor %}
        {% endif %}
        {% if is_edit %}
        <form method="POST" enctype="multipart/form-data" action="{% url 'posts:post_edit' post.pk %}">
        {% else %}
          <form method="POST" enctype="multipart/form-data" action="{% url 'posts:post_create' %}">
        {% endif %}
        {% csrf_token %}
            {% for field in form %}
            <div class="form-group row my-3 p-3">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">
                    *
                  </span>
                {% endif %}
              </label>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
            </div>
          {% endfor %}
          <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">
              {% if is_edit %}
                Сохранить
              {% else %}
                Добавить
              {% endif %}
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}
  Мои подписки
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Мои подписки</h1>
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: <a href="{% url 'posts:profile' post.author.username %}">
            {{ post.author.get_full_name }} </a>
            {% if not post.author.get_full_name %}
              <a href="{% url 'posts:profile' post.author.username %}"> Аноним </a>
            {% endif %}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text|linebreaksbr }}
        </p>
        {% if post.group %}
          <a href="{% url 'posts:group_lists' post.group.slug %}">
            все записи группы {{ post.group }}
          </a>
        {% endif %}
        <br>
        {% if post.author %}
          <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
        {% endif %}
      </article>
      {% if not forloop.last %}
      <hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  {{ group.title}}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>
      {{ group.description|linebreaksbr }}
    </p>
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: <a href="{% url 'posts:profile' post.author.username %}">
            {{ post.author.get_full_name }} </a>
            {% if not post.author.get_full_name %}
              <a href="{% url 'posts:profile' post.author.username %}"> Аноним </a>
            {% endif %}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text|linebreaksbr }}
        </p>
        {% if post.author %}
          <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
        {% endif %}
      </article>
      {% if not forloop.last %}
      <hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Последние обновления на сайте</h1>
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: <a href="{% url 'posts:profile' post.author.username %}">
            {{ post.author.get_full_name }} </a>
            {% if not post.author.get_full_name %}
              <a href="{% url 'posts:profile' post.author.username %}"> Аноним </a>
            {% endif %}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text|linebreaksbr }}
        </p>
        {% if post.group %}
          <a href="{% url 'posts:group_lists' post.group.slug %}">
            все записи группы {{ post.group }}
          </a>
        {% endif %}
        <br>
        {% if post.author %}
          <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
        {% endif %}
      </article>
      {% if not forloop.last %}
      <hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load user_filters %}
{% load thumbnail %}
{% block title %}
  Пост {{ posts.text|truncatechars:30 }}
{% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ posts.pub_date|date:"d E Y" }}
        </li>
        {% if posts.group %}
          <li class="list-group-item">
            Группа:
            <a href="{% url 'posts:group_lists' posts.group.slug %}">
              все записи группы {{ posts.group }}
            </a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ posts.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span > {{ posts.author.posts.count }} </span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' posts.author.username %}">все посты пользователя</a>
        </li>
      </ul>
    </aside>
    {% thumbnail posts.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <article class="col-12 col-md-9">
      <p>
        {{ posts.text|linebreaks }}
      </p>
      {% if request.user == posts.author %}
        <a class='btn btn-primary' href="{% url 'posts:post_edit' posts.pk %}">
          Редактировать запись
        </a>
      {% endif %}
    </article>
    {% include 'posts/includes/comment.html' %}
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}
  Профиль пользователя
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Все посты пользователя {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ author.posts.count }} </h3>
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
      {% endif %}
      <article>
      {% for post in page_obj %}
        <ul>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text|linebreaksbr }}
        </p>
        {% if post.author %}
          <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
        {% endif %}
        <br>
        {% if post.group %}
          <a href="{% url 'posts:group_lists' post.group.slug %}">
            все записи группы {{ post.group }}
          </a>
        {% endif %}
      </article>
      {% if not forloop.last %}
      <hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}